apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-datasources
  namespace: prometheus
  labels:
    app.kubernetes.io/name: prometheus
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: prometheus
      type: prometheus
      url: http://prometheus-prometheus:9090
      version: 1
