apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-dashboardproviders
  labels:
    app.kubernetes.io/name: prometheus
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      editable: true
      folder: ""
      name: default
      options:
        path: /var/lib/grafana/dashboards
      orgId: 1
      type: file