apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-state-metrics
  labels:
    k8s-app: kube-state-metrics
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: kube-state-metrics
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  - name: telemetry
    port: 8081
    targetPort: telemetry
    protocol: TCP
  selector:
